/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Category, Transaction, Budget } from './types';

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 't-1',
    payee: 'Whole Foods Market',
    category: Category.FOOD,
    amount: -84.20,
    type: 'expense',
    date: '2026-06-10', // today
    time: '02:45 PM',
    notes: 'Weekly fresh groceries',
    account: 'Main Checking',
  },
  {
    id: 't-2',
    payee: 'City Transit Card',
    category: Category.TRANSPORT,
    amount: -15.00,
    type: 'expense',
    date: '2026-06-09', // yesterday
    time: '05:30 PM',
    notes: 'Metro card auto-refill',
    account: 'Main Checking',
  },
  {
    id: 't-3',
    payee: 'Salary Deposit',
    category: Category.INCOME,
    amount: 4200.00,
    type: 'income',
    date: '2026-06-05', // few days ago
    time: '09:00 AM',
    notes: 'Monthly corporate salary payout',
    account: 'Main Checking',
  },
  {
    id: 't-4',
    payee: 'The Coffee Bean',
    category: Category.FOOD,
    amount: -6.50,
    type: 'expense',
    date: '2026-06-04',
    time: '08:15 AM',
    notes: 'Iced latte & croissant',
    account: 'Main Checking',
  },
  {
    id: 't-5',
    payee: 'Shell Gas Station',
    category: Category.TRANSPORT,
    amount: -55.00,
    type: 'expense',
    date: '2026-06-09', // yesterday
    time: '06:15 PM',
    notes: 'Fuel tank refill',
    account: 'Main Checking',
  },
  {
    id: 't-6',
    payee: 'Blue Sushi Sake Grill',
    category: Category.FOOD,
    amount: -89.45,
    type: 'expense',
    date: '2026-06-09', // yesterday
    time: '01:20 PM',
    notes: 'Dinner with colleagues',
    account: 'Credit Card',
  },
  {
    id: 't-7',
    payee: 'Netflix Subscription',
    category: Category.FUN,
    amount: -15.99,
    type: 'expense',
    date: '2026-06-09', // yesterday
    time: '08:00 AM',
    notes: 'Premium Ultra HD plan',
    account: 'Credit Card',
  },
  {
    id: 't-8',
    payee: 'Apple Store',
    category: Category.FUN,
    amount: -1299.00,
    type: 'expense',
    date: '2026-06-01',
    time: '02:30 PM',
    notes: 'iPad Pro M4 replacement',
    account: 'Savings',
  },
  // May 2026
  {
    id: 't-m1',
    payee: 'Salary Deposit',
    category: Category.INCOME,
    amount: 4200.00,
    type: 'income',
    date: '2026-05-05',
    time: '09:00 AM',
    notes: 'Monthly corporate salary payout',
    account: 'Main Checking',
  },
  {
    id: 't-m2',
    payee: 'Metropolitan Rent',
    category: Category.HOUSING,
    amount: -2350.00,
    type: 'expense',
    date: '2026-05-01',
    time: '10:00 AM',
    notes: 'Monthly apartment rent payment',
    account: 'Main Checking',
  },
  {
    id: 't-m3',
    payee: 'Trader Joe\'s Groceries',
    category: Category.FOOD,
    amount: -340.50,
    type: 'expense',
    date: '2026-05-12',
    time: '04:15 PM',
    notes: 'Stocking up pantry & snacks',
    account: 'Main Checking',
  },
  {
    id: 't-m4',
    payee: 'Chevron Station',
    category: Category.TRANSPORT,
    amount: -50.00,
    type: 'expense',
    date: '2026-05-15',
    time: '11:30 AM',
    notes: 'Fuel',
    account: 'Main Checking',
  },
  {
    id: 't-m5',
    payee: 'Coachella Spring Festival',
    category: Category.FUN,
    amount: -549.00,
    type: 'expense',
    date: '2026-05-18',
    time: '01:10 PM',
    notes: 'Seasonal concert passes & fun',
    account: 'Credit Card',
  },
  {
    id: 't-m6',
    payee: 'Whole Foods Market',
    category: Category.FOOD,
    amount: -180.20,
    type: 'expense',
    date: '2026-05-24',
    time: '06:30 PM',
    notes: 'Organic groceries',
    account: 'Credit Card',
  },
  // April 2026
  {
    id: 't-a1',
    payee: 'Salary Deposit',
    category: Category.INCOME,
    amount: 4200.00,
    type: 'income',
    date: '2026-04-05',
    time: '09:00 AM',
    notes: 'Monthly salary',
    account: 'Main Checking',
  },
  {
    id: 't-a2',
    payee: 'Metropolitan Rent',
    category: Category.HOUSING,
    amount: -2350.00,
    type: 'expense',
    date: '2026-04-01',
    time: '10:00 AM',
    notes: 'Rent',
    account: 'Main Checking',
  },
  {
    id: 't-a3',
    payee: 'Sprout Groceries',
    category: Category.FOOD,
    amount: -290.00,
    type: 'expense',
    date: '2026-04-10',
    time: '01:20 PM',
    notes: 'Weekly food',
    account: 'Main Checking',
  },
  {
    id: 't-a4',
    payee: 'Subway Pass',
    category: Category.TRANSPORT,
    amount: -60.00,
    type: 'expense',
    date: '2026-04-12',
    time: '08:00 AM',
    notes: 'Monthly pass auto-refill',
    account: 'Main Checking',
  },
  {
    id: 't-a5',
    payee: 'Dental Cleaning Clinic',
    category: Category.HEALTH,
    amount: -125.00,
    type: 'expense',
    date: '2026-04-18',
    time: '11:00 AM',
    notes: 'Regular six-month cleanup dental visit',
    account: 'Credit Card',
  },
  {
    id: 't-a6',
    payee: 'AMC Theatre Ticketing',
    category: Category.FUN,
    amount: -45.00,
    type: 'expense',
    date: '2026-04-20',
    time: '07:30 PM',
    notes: 'Movie night with popcorn',
    account: 'Credit Card',
  },
  // March 2026
  {
    id: 't-mr1',
    payee: 'Salary Deposit',
    category: Category.INCOME,
    amount: 4200.00,
    type: 'income',
    date: '2026-03-05',
    time: '09:00 AM',
    notes: 'Monthly salary',
    account: 'Main Checking',
  },
  {
    id: 't-mr2',
    payee: 'Metropolitan Rent',
    category: Category.HOUSING,
    amount: -2350.00,
    type: 'expense',
    date: '2026-03-01',
    time: '10:00 AM',
    notes: 'Rent',
    account: 'Main Checking',
  },
  {
    id: 't-mr3',
    payee: 'Whole Foods Market',
    category: Category.FOOD,
    amount: -320.40,
    type: 'expense',
    date: '2026-03-11',
    time: '05:40 PM',
    notes: 'Groceries',
    account: 'Main Checking',
  },
  {
    id: 't-mr4',
    payee: 'Uber & Lyft Rides',
    category: Category.TRANSPORT,
    amount: -85.50,
    type: 'expense',
    date: '2026-03-15',
    time: '11:55 PM',
    notes: 'Rainy weekend transport rides',
    account: 'Credit Card',
  },
  {
    id: 't-mr5',
    payee: 'Ski Resort Weekend',
    category: Category.FUN,
    amount: -390.00,
    type: 'expense',
    date: '2026-03-18',
    time: '08:00 AM',
    notes: 'Lift tickets & ski equipment rental',
    account: 'Credit Card',
  },
  // February 2026
  {
    id: 't-f1',
    payee: 'Salary Deposit',
    category: Category.INCOME,
    amount: 4200.00,
    type: 'income',
    date: '2026-02-05',
    time: '09:00 AM',
    notes: 'Salary',
    account: 'Main Checking',
  },
  {
    id: 't-f2',
    payee: 'Metropolitan Rent',
    category: Category.HOUSING,
    amount: -2350.00,
    type: 'expense',
    date: '2026-02-01',
    time: '10:00 AM',
    notes: 'Rent',
    account: 'Main Checking',
  },
  {
    id: 't-f3',
    payee: 'Trader Joe\'s Groceries',
    category: Category.FOOD,
    amount: -280.12,
    type: 'expense',
    date: '2026-02-08',
    time: '02:30 PM',
    notes: 'Weekly run',
    account: 'Main Checking',
  },
  {
    id: 't-f4',
    payee: 'Shell Petrol Station',
    category: Category.TRANSPORT,
    amount: -55.00,
    type: 'expense',
    date: '2026-02-12',
    time: '04:15 PM',
    notes: 'Car refill',
    account: 'Main Checking',
  },
  {
    id: 't-f5',
    payee: 'Valentine Dinner Date',
    category: Category.FUN,
    amount: -210.00,
    type: 'expense',
    date: '2026-02-14',
    time: '08:30 PM',
    notes: 'Romantic dinner at Le Petit',
    account: 'Credit Card',
  },
  // January 2026
  {
    id: 't-j1',
    payee: 'Salary Deposit',
    category: Category.INCOME,
    amount: 4200.00,
    type: 'income',
    date: '2026-01-05',
    time: '09:00 AM',
    notes: 'Salary',
    account: 'Main Checking',
  },
  {
    id: 't-j2',
    payee: 'Metropolitan Rent',
    category: Category.HOUSING,
    amount: -2350.00,
    type: 'expense',
    date: '2026-01-01',
    time: '10:00 AM',
    notes: 'Rent',
    account: 'Main Checking',
  },
  {
    id: 't-j3',
    payee: 'Whole Foods Market',
    category: Category.FOOD,
    amount: -310.50,
    type: 'expense',
    date: '2026-01-10',
    time: '04:00 PM',
    notes: 'New Year groceries',
    account: 'Main Checking',
  },
  {
    id: 't-j4',
    payee: 'Subway Pass',
    category: Category.TRANSPORT,
    amount: -60.00,
    type: 'expense',
    date: '2026-01-12',
    time: '08:00 AM',
    notes: 'Pass refill',
    account: 'Main Checking',
  },
  {
    id: 't-j5',
    payee: 'New Year Party Lounge',
    category: Category.FUN,
    amount: -280.00,
    type: 'expense',
    date: '2026-01-01',
    time: '01:30 AM',
    notes: 'Celebration drinks & entry ticket',
    account: 'Credit Card',
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'b-1',
    category: Category.FOOD,
    name: 'Groceries',
    limit: 1200.00,
    spent: 850.00, // 70.8%
    status: 'healthy',
    notes: 'Monthly grocery limit',
  },
  {
    id: 'b-2',
    category: Category.FUN,
    name: 'Entertainment',
    limit: 400.00,
    spent: 120.00, // 30% Used
    status: 'healthy',
    notes: "You're spending 15% less than your usual trend in this category.",
  },
  {
    id: 'b-3',
    category: Category.HOUSING,
    name: 'Housing',
    limit: 2500.00,
    spent: 2350.00, // 94% Used
    status: 'critical',
    notes: 'Only $150.00 remaining for utility bills.',
  },
  {
    id: 'b-4',
    category: Category.FUN,
    name: 'Summer Trip',
    limit: 2500.00,
    spent: 300.00, // 12% Used
    status: 'saving',
    notes: 'Saving phase',
  },
];

export const WEEKLY_SPENDING_DATA = [
  { day: 'M', amount: 48 },
  { day: 'T', amount: 82 },
  { day: 'W', amount: 35 },
  { day: 'T', amount: 160 },
  { day: 'F', amount: 120 },
  { day: 'S', amount: 95 },
  { day: 'S', amount: 190 },
];
